GET http://localhost:3000/animals/all/mood

###

GET http://localhost:3000/animals/cat/mood

###

PUT http://localhost:3000/animals/cat/soffan

###

PUT http://localhost:3000/animals/cat/felix

###

PUT http://localhost:3000/animals/camel/George/mood
Content-Type: application/json

{
    "mood": "happy"
}

###

DELETE http://localhost:3000/animals/cat/felix

###

POST http://localhost:3000/animals/cat/soffan/feed