GET http://localhost:3000/animals/all/mood

###

GET http://localhost:3000/animals/cow/mood

###

PUT http://localhost:3000/animals/cat/fifi

###

PUT http://localhost:3000/animals/cat/felix

###

PUT http://localhost:3000/animals/cat/fifi/mood
Content-Type: application/json

{
    "mood": "happy"
}